services:
  minitwit:
    build: .
    image: my_minitwit_image
    ports:
      - "8080:5000"
    volumes:
      - minitwit_data:/app/tmp
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

  clidownload:
    image: curlimages/curl
    depends_on:
      minitwit:
        condition: service_healthy
    entrypoint: sh -c "curl -s http://minitwit:5000"

volumes:
  minitwit_data: