services:
  minitwit:
    image: michaelfant/minitwitimage:latest
    ports:
      - "8080:5000"
    volumes:
      - minitwit_data:/app/tmp
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 10s
      retries: 3

  flagtool:
    image: michaelfant/flagtoolimage:latest
    volumes:
      - minitwit_data:/app/tmp
    restart: always

volumes:
  minitwit_data: